// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlTXolEU9J-R6BH36zoh2qiBiz65ShrKM',
    appId: '1:560695299113:web:7503135c965350ed3f2038',
    messagingSenderId: '560695299113',
    projectId: 'azscrap-70ada',
    authDomain: 'azscrap-70ada.firebaseapp.com',
    databaseURL: 'https://azscrap-70ada-default-rtdb.firebaseio.com',
    storageBucket: 'azscrap-70ada.appspot.com',
    measurementId: 'G-QPFWFXKJXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrBamK0Nrx-fegUlMgXbB36oSQlHSTDxg',
    appId: '1:560695299113:android:4568e3805a23cec23f2038',
    messagingSenderId: '560695299113',
    projectId: 'azscrap-70ada',
    databaseURL: 'https://azscrap-70ada-default-rtdb.firebaseio.com',
    storageBucket: 'azscrap-70ada.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7B78q4p7IB8OsiIXqKduhoLWaDSdrKxM',
    appId: '1:560695299113:ios:b6bd3efc21d925573f2038',
    messagingSenderId: '560695299113',
    projectId: 'azscrap-70ada',
    databaseURL: 'https://azscrap-70ada-default-rtdb.firebaseio.com',
    storageBucket: 'azscrap-70ada.appspot.com',
    androidClientId: '560695299113-rkseh6ccatmuu4aenrrl2mhe4puo87cd.apps.googleusercontent.com',
    iosClientId: '560695299113-u1tpi9oj4l4i6dvqnc7h6nfp9439c7tk.apps.googleusercontent.com',
    iosBundleId: 'com.example.azscrap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7B78q4p7IB8OsiIXqKduhoLWaDSdrKxM',
    appId: '1:560695299113:ios:b6bd3efc21d925573f2038',
    messagingSenderId: '560695299113',
    projectId: 'azscrap-70ada',
    databaseURL: 'https://azscrap-70ada-default-rtdb.firebaseio.com',
    storageBucket: 'azscrap-70ada.appspot.com',
    androidClientId: '560695299113-rkseh6ccatmuu4aenrrl2mhe4puo87cd.apps.googleusercontent.com',
    iosClientId: '560695299113-u1tpi9oj4l4i6dvqnc7h6nfp9439c7tk.apps.googleusercontent.com',
    iosBundleId: 'com.example.azscrap',
  );
}
